openapi: 3.0.3
info:
  title: 情報工学実験のアプリ
  description: ''
  version: v0.1.0
servers:
  - url: https://example.com/api/v1/
paths:
  /upload:
    post:
      summary: 写真のアップロード先
      description: ''
      operationId: ''
      requestBody:
        description: 画像をbase64エンコードしてJSONに詰めて送る
        content:
          application/json:
            schema:
              type: object
              properties:
                attatchment:
                  type: object
                  properties:
                    base64:
                      type: string
            examples:
              例1:
                value: |
                  {
                    "attatchment": {
                      "base64": "TWFuIGlzIGRpc3Rpbmd1aXNoZWQsIG5vdCB..."
                    }
                  }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  price:
                    type: number
                  kcal:
                    type: number
                  protein:
                    type: number
                  fat:
                    type: number
                  carbonhydrate:
                    type: number
                  salt:
                    type: number
                  calcium:
                    type: number
                  vegetable:
                    type: number
              examples:
                例1:
                  value: |
                    {
                      "menus": [
                        {
                          "name": "バンバンジー豆腐",
                          "price": 132,
                          "kcal": 134,
                          "protein": 10.2,
                          "fat": 7.4,
                          "carbohydrate": 7.8,
                          "salt": 1.2,
                          "calcium": 3,
                          "vegetable": 30
                        },
                        {
                          "name": "バンバンジー豆腐",
                          "price": 132,
                          "kcal": 134,
                          "protein": 10.2,
                          "fat": 7.4,
                          "carbohydrate": 7.8,
                          "salt": 1.2,
                          "calcium": 3,
                          "vegetable": 30
                        }
                      ],
                      "sum": {
                        "price": 264,
                        "kcal": 268,
                        "protein": 20.4,
                        "fat": 14.8,
                        "carbohydrate": 15.6,
                        "salt": 2.4,
                        "calcium": 6,
                        "vegetable": 60
                      }
                    }
                    
